### ISSUE TITLE
Hide from results support

### ISSUE THREAD

**Issue by jimthedev** [mrjoelkemp/node-list-dependencies#3]
Hello, sometimes I have a bower_components or jspm_components folder in my public directory that I don't really want included in the result list of dependencies but I do want to be 'known' to the dependency map so that errors aren't thrown. Would it be possible to allow for explicit folders paths to be hidden or excluded from the results?

**Comment by mrjoelkemp** [comment]
Hi @jimthedev. Thanks for contributing!

It's totally possible, but the solutions really boil down to a regex test to determine whether or not to print a path. If that's really the case, then this is the same as using `sed` with the `d` command to delete lines based on a regex. Would piping the output from `list-dependencies` into `sed` suffice for your needs?

**Comment by jimthedev** [comment]
@mrjoelkemp Good idea! I'll give this a shot and report back with a command that fulfills this.

**Comment by mrjoelkemp** [comment]
@jimthedev awesome. I'll close this for now. Looking forward to hearing back if `sed` suffices.
